/*
 * Copyright 2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.alibaba.cloud.ai.headless.api.pojo;

import lombok.Data;

import java.io.Serializable;

@Data
public class SqlInfo implements Serializable {
    private static final long serialVersionUID = 1L;

    // S2SQL generated by semantic parsers
    private String parsedS2SQL;

    // S2SQL corrected by semantic correctors
    private String correctedS2SQL;

    // SQL to be executed finally
    private String querySQL;

    // Physical SQL corrected by LLM for performance optimization
    private String correctedQuerySQL;
}
